### ISSUE TITLE
Eslint Setup

### ISSUE THREAD

**Issue by jnmorse** [croraf/orderme#5]
Eslint in its current configuration complains a lot about not having prop types defined on most all the components in the frontend. I had started to work on a rather large number of changes to try to address this the other night, but was wondering if would rather just turn the rule off in the eslint config if they are not going to be used.

```json
{
    "rules": {
        "react/prop-types": "off"
    }
}
```

https://github.com/jnmorse/orderme/tree/linting-fixes

**Comment by croraf** [comment]
Indeed. This is a good idea to temporarily turn them off. I plan to use them later, but probably in the meantime this is a way to go.
